SELECT rc.Id
      ,rc.SyncId
      ,rc.SourceRugId
      ,rc.SourceCertId
      ,rc.CertificateNumber
      ,rc.CertificateSerial
      ,rc.RugCode
      ,rc.ProducerUserId
      ,rc.CreatorUserId
      ,rc.DesignerUserId
      ,rc.MasterWeaverUserId
      ,rc.NumberOfColors
      ,rc.WidthInCm
      ,rc.HeightInCm
      ,rc.AreaMSq
      ,rc.DensityUnitInCm
      ,rc.DensityRaj
      ,rc.DensityIn10CmSq
      ,rc.NumberOfKnotsInWidth
      ,rc.NumberOfKnotsInLength
      ,rc.TotalNumberOfKnots
      ,rc.ManHoursOfWeave
      ,rc.NumberOfWeavers
      ,rc.DurationOfCreationInMonth
      ,rc.Weight
      ,rc.LastUpdate
      ,rc.ImagePath
      ,rc.CertType
      ,rc.IssueDate
      ,rc.IsExpired
      ,rc.UserRugCode
      ,rc.CertVersion
      ,rc.UncertainCreateYear
      ,rcl.Id
      ,rcl.RugCertificationId
      ,rcl.LanguageId
      ,rcl.OwnerName
      ,rcl.YearOfCreation
      ,rcl.Producer
      ,rcl.Creator
      ,rcl.PlaceOfCreation
      ,rcl.Designer
      ,rcl.MasterWeaver
      ,rcl.WeaveMethod
      ,rcl.KnotType
      ,rcl.PileMaterial
      ,rcl.WarpMaterial
      ,rcl.WeftMaterial
      ,rcl.DesignType
      ,rcl.DesignName
      ,rcl.GroundColor
      ,rcl.BorderColor
      ,rcl.Description
      ,rcl.LastUpdate
      ,rcl.RequestType
      ,rcl.ConfirmationRef
      ,rcl.Expert
      ,rcl.CertStatus
      ,rcl.PlaceOfWeave
      ,rcl.HandWovenType
      ,rcl.StyleCity
      ,rcl.SuspensionText
      ,rcl.Nationality
FROM RugCertification AS rc
LEFT JOIN RugCertificationLocalize AS rcl	ON rc.Id = rcl.RugCertificationId
